/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ContactForm {}
}

declare global {


  interface HTMLContactFormElement extends Components.ContactForm, HTMLStencilElement {}
  var HTMLContactFormElement: {
    prototype: HTMLContactFormElement;
    new (): HTMLContactFormElement;
  };
  interface HTMLElementTagNameMap {
    'contact-form': HTMLContactFormElement;
  }
}

declare namespace LocalJSX {
  interface ContactForm extends JSXBase.HTMLAttributes<HTMLContactFormElement> {}

  interface IntrinsicElements {
    'contact-form': ContactForm;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


